# Basic options
default_keybindings = false
use_nerdfont = true
notify = true
gapless = true
flip_status_indicators=true
shuffle = false
repeat = 'playlist'
statusbar_format = "%artists - %title"

[keybindings]

##################
# Fast forward / rewind
##################
"b" = "seek -1000"
"f" = "seek +1000"
"B" = "seek -10000"
"F" = "seek +10000"

##################
# Play / pause
##################
"p" = "playpause"
"Enter" = "play"
"s" = "stop"


##################
# Track manipulation
##################
"H" = "previous"
"L" = "next"
"r" = "repeat"
"z" = "shuffle"
"D" = "delete"
"S" = "save"
# Open context menu
"O" = "open current"
"o" = "open selected"
"A" = "goto artist"
"a" = "goto album"

##################
# Queue
##################
# Add to queue
" " = "queue"
"Ctrl+s" = "save queue"
# Move selected song up/down in the queue
"J" = "shift down 1"
"K" = "shift up 1"
"C" = "clear"
# Open the context menu for a Spotify link in the clipboard
"Ctrl+v" = "insert"

######################################
# Sound
######################################
"=" = "volup 1"
"-" = "voldown 1"
"[" = "volup 5"
"]" = "voldown 5"

######################################
# Movements
######################################
"F1" = "focus queue"
"F2" = "focus library"
"F3" = "focus search"
"1" = "focus queue"
"2" = "focus library"
"Ctrl+q" = "focus queue"
# Go to the playing track
"." = "move playing"
# Navigation
"Down" = "move down 1"
"G" = "move bottom"
"g" = "move top"
"Left" = "move left 1"
"Right" = "move right 1"
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"Up" = "move up 1"
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"Ctrl+e" = "move down 1"
"Ctrl+y" = "move up 1"
"l" = "move right 1"
"." = "move playing"
"q" = "back"

######################################
# Sorting
######################################
"t" = "sort added d"
"T" = "sort title a"

######################################
# Sharing
######################################
"Y" = "share selected"
"y" = "share current"

######################################
# Other
######################################
"Q" = "quit"
"Z" = "quit"
"?" = "help"
"U" = "update"
"q" = "noop"

[track_format]
left = "%artists - %title"
center = "%album"
right = "%saved %duration"

[notification_format]
title = "%title"
body = "%artists"

# Gruvbox dark by Dajonaga [ background = "default" to enjoy terminal transparency ]
[theme]
#background = "#282828"
background = "default"
primary = "#EBDBB2"
secondary = "#D5C4A1"
title = "#D65D0E"
playing = "#B16286"
playing_selected = "#458588"
playing_bg = "#1D2021"
highlight = "#D79921"
highlight_bg = "#1D2021"
error = "#FBF1C7"
error_bg = "#CC241D"
statusbar = "#282828"
statusbar_progress = "#689D6A"
statusbar_bg = "#98971A"
cmdline = "#1D2021"
cmdline_bg = "#FE8019"
search_match = "#fabd2f"

